Edit docs/learn/wallets/firefly-wallet.md
iota-community/iota-wiki pull request #269
Opened 2021-09-28 12:26 UTC by DafPhil

2021-09-28 21:28 UTC, Dr-Electron requested changes

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![wallet detail view](/img/learn/firefly/wallet_detail_view.png)
```suggestion
[![wallet detail view](/img/learn/firefly/wallet_detail_view.png)](/img/learn/firefly/wallet_detail_view.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![transaction details view](/img/learn/firefly/transaction_details_view.png)
```suggestion
[![transaction details view](/img/learn/firefly/transaction_details_view.png)](/img/learn/firefly/transaction_details_view.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![setup a wallet ledger](/img/learn/firefly/setup_a_wallet_ledger.png)
```suggestion
[![setup a wallet ledger](/img/learn/firefly/setup_a_wallet_ledger.png)](/img/learn/firefly/setup_a_wallet_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![create a wallet ledger](/img/learn/firefly/create_a_wallet_ledger.png)
```suggestion
[![create a wallet ledger](/img/learn/firefly/create_a_wallet_ledger.png)](/img/learn/firefly/create_a_wallet_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![set pin ledger](/img/learn/firefly/set_pin_ledger.png)
```suggestion
[![set pin ledger](/img/learn/firefly/set_pin_ledger.png)](/img/learn/firefly/set_pin_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![connect ledger ledger](/img/learn/firefly/connect_ledger.png)
```suggestion
[![connect ledger ledger](/img/learn/firefly/connect_ledger.png)](/img/learn/firefly/connect_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![setup complete ledger](/img/learn/firefly/setup_complete_ledger.png)
```suggestion
[![setup complete ledger](/img/learn/firefly/setup_complete_ledger.png)](/img/learn/firefly/setup_complete_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![generate address ledger](/img/learn/firefly/generate_address_ledger.png)
```suggestion
[![generate address ledger](/img/learn/firefly/generate_address_ledger.png)](/img/learn/firefly/generate_address_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![confirm receive address ledger](/img/learn/firefly/confirm_receive_address_ledger.png)
```suggestion
[![confirm receive address ledger](/img/learn/firefly/confirm_receive_address_ledger.png)](/img/learn/firefly/confirm_receive_address_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![display ledger address](/img/learn/firefly/display_ledger_address.png)![okay ledger display](/img/learn/firefly/okay_ledger_display.png)
```suggestion
[![display ledger address](/img/learn/firefly/display_ledger_address.png)](/img/learn/firefly/display_ledger_address.png) [![okay ledger display](/img/learn/firefly/okay_ledger_display.png)](/img/learn/firefly/okay_ledger_display.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![wallet view ledger](/img/learn/firefly/wallet_view_ledger.png)
```suggestion
[![wallet view ledger](/img/learn/firefly/wallet_view_ledger.png)](/img/learn/firefly/wallet_view_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![send payment ledger](/img/learn/firefly/send_payment_ledger.png)
```suggestion
[![send payment ledger](/img/learn/firefly/send_payment_ledger.png)](/img/learn/firefly/send_payment_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![confirm remainder address ledger](/img/learn/firefly/confirm_remainder_address_ledger.png)![confirm transaction ledger](/img/learn/firefly/confirm_transaction_ledger.png)![dispaly amount ledger](/i
```suggestion
[![confirm remainder address ledger](/img/learn/firefly/confirm_remainder_address_ledger.png)](/img/learn/firefly/confirm_remainder_address_ledger.png)[![confirm transaction ledger](/img/learn/firefly/confirm_transaction_ledger.png)](/img/learn/firefly/confirm_transaction_ledger.png)[![dispaly amount ledger](/img/learn/firefly/dispaly_amount_ledger.png)](/img/learn/firefly/dispaly_amount_ledger.png)[![display accept ledger](/img/learn/firefly/display_accept_ledger.png)](/img/learn/firefly/display_accept_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![multiple wallet view ledger](/img/learn/firefly/multiple_wallet_view_ledger.png)
```suggestion
[![multiple wallet view ledger](/img/learn/firefly/multiple_wallet_view_ledger.png)](/img/learn/firefly/multiple_wallet_view_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![choose send from wallet ledger](/img/learn/firefly/choose_send_from_wallet_ledger.png)
```suggestion
[![choose send from wallet ledger](/img/learn/firefly/choose_send_from_wallet_ledger.png)](/img/learn/firefly/choose_send_from_wallet_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![setup a wallet1 ledger](/img/learn/firefly/setup_a_wallet_ledger.png)![create a wallet1 ledger](/img/learn/firefly/create_a_wallet_ledger.png)
```suggestion
[![setup a wallet1 ledger](/img/learn/firefly/setup_a_wallet_ledger.png)](/img/learn/firefly/setup_a_wallet_ledger.png)[![create a wallet1 ledger](/img/learn/firefly/create_a_wallet_ledger.png)](/img/learn/firefly/create_a_wallet_ledger.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +![ledger multiple profile view](/img/learn/firefly/ledger_multiple_profile_view.png)
```suggestion
[![ledger multiple profile view](/img/learn/firefly/ledger_multiple_profile_view.png)](/img/learn/firefly/ledger_multiple_profile_view.png)
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +If your Ledger device does not show “generating address…” while finding balances then try disconnecting and reconnecting the device. In rare cases, where you used an old version of the legacy app you
```suggestion
If your Ledger device does not show “Generating address…” while finding balances then try disconnecting and reconnecting the device. In rare cases, where you used an old version of the legacy app you may need to uninstall and reinstall the legacy app. Return to Ledger Live and reinstall this application on your Ledger device and try again.
```

2021-09-28 21:28 UTC, Dr-Electron commented on docs/learn/wallets/firefly-wallet.md
> +If your Ledger device does not show “generating address…” while finding balances then try disconnecting and reconnecting the device. In rare cases, where you used an old version of the legacy app you
This is a sentence from the ledger display. So it is fine as it is

2021-09-30 01:46 UTC, Phyloiota approved these changes

2021-10-01 12:39 UTC, Dr-Electron approved these changes

2021-10-01 12:41 UTC, merged