Edit internal/participate/use-cases/mobility.md
iota-community/iota-wiki pull request #433
Opened 2022-01-09 16:31 UTC by rohste

2022-01-12 02:00 UTC, Critical94 commented
Thanks for your contribution! I added some link text and changed the MOBI headline, I hope this is ok for you.

2022-01-12 02:05 UTC, Critical94 approved these changes

2022-01-13 12:58 UTC, jlvandenhout requested changes

2022-01-13 12:58 UTC, jlvandenhout commented on internal/participate/use-cases/mobility.md
> +The EDAG CityBot is a multi-functional, fully autonomous robot vehicle with swarm intelligence, which is completely emission-free. EDAG CityBots are an integral part of a complete smart city operatin
```suggestion
The EDAG CityBot is a multi-functional, fully autonomous robot vehicle with swarm intelligence, which is completely emission-free. EDAG CityBots are an integral part of a complete smart city operating system. EDAG Engineering Group AG roughly has 8000 employees and more than 60 locations worldwide.
```

2022-01-13 12:58 UTC, jlvandenhout commented on internal/participate/use-cases/mobility.md
> +Filancore is a German based company with the mission to manage Industrial IoT in the most secure & efficient way in areas such as Automotive/Mobility, Health Care, Smart City, Industrial, Environment
```suggestion
Filancore is a German based company with the mission to manage Industrial IoT in the most secure and efficient way in areas such as Automotive and Mobility, Health Care, Smart City, Industrial, Environmental and Farming, Smart Home and Smart Building.
```

2022-01-16 00:32 UTC, jlvandenhout approved these changes

2022-01-16 00:33 UTC, merged