Add Images
iota-community/iota-wiki pull request #488
Opened 2022-03-21 17:24 UTC by JSto91

# Description of change

Add Banner for Participate-Section
Pages:
- About Nodes
- Become a node operator
- Node Software
- X - Teams
- EDF

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

2022-03-22 21:41 UTC, Dr-Electron approved these changes
LGTM. But we need to check if the banners work as social previews. We can check that after you published a build :)

2022-03-22 21:46 UTC, Critical94 approved these changes
LGTM

2022-03-22 21:48 UTC, Dr-Electron requested changes
Don't forget too look at preview images

2022-03-31 06:56 UTC, Dr-Electron approved these changes

2022-03-31 06:56 UTC, merged