Feat/hornet inx interface tutorial
iota-community/iota-wiki pull request #683
Opened 2022-08-03 12:54 UTC by adrian-grassl

# Description of change

Added a single-page tutorial to showcase interaction with the IOTA Node Extension (INX) gRPC interface.

## Links to any relevant issues

No

## Type of change

Documentation Enhancement

## How the change has been tested

Wiki was tested locally

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ x ] I have followed the contribution guidelines for this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have tested the wiki locally and tested that all external links work

2022-08-03 22:10 UTC, Dr-Electron requested changes
I would say and recommend/request the same stuff here as in your other tutorial :)

2022-08-03 22:17 UTC, Dr-Electron commented
@iota-community/if-technical-writers

2022-08-04 11:18 UTC, lucas-tortora approved these changes
Just some silly formatting comments, awesome work :) !

2022-08-04 11:18 UTC, lucas-tortora commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +In this tutorial you will learn how to interact with the IOTA Node Extension ([INX](https://github.com/iotaledger/inx)) Interface via javascript (NodeJS) with both simple requests and streaming reque
```suggestion
In this tutorial, you will learn how to interact with the IOTA Node Extension ([INX](https://github.com/iotaledger/inx)) Interface via javascript (NodeJS) with both simple requests and streaming requests. The extension uses the [inx.proto](https://github.com/iotaledger/inx/blob/develop/proto/inx.proto) file to generate the required gRPC client to connect to HORNET. [gRPC](https://grpc.io/) is a modern open source high performance Remote Procedure Call (RPC) framework that can run in any environment.
```

2022-08-04 11:18 UTC, lucas-tortora commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
>  # INX Interface Interaction
```suggestion
# INX Interface Interaction

```

2022-08-04 11:18 UTC, lucas-tortora commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +### Prerequisites
```suggestion
### Prerequisites

```

2022-08-04 11:18 UTC, lucas-tortora commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
>  #### Prepare development environment
```suggestion
#### Prepare development environment

```

2022-08-04 11:18 UTC, lucas-tortora commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
>  #### Prepare proto file
```suggestion
#### Prepare proto file

```

2022-08-04 11:18 UTC, lucas-tortora commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +### Run
```suggestion
### Run

```

2022-08-04 23:41 UTC, Dr-Electron approved these changes

2022-08-08 09:32 UTC, aleksei-korolev requested changes

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +In this tutorial, you will learn how to interact with the IOTA Node Extension ([INX](https://github.com/iotaledger/inx)) Interface via javascript (NodeJS) with both simple requests and streaming requ
```suggestion
In this tutorial, you will learn how to interact with the IOTA Node Extension ([INX](https://github.com/iotaledger/inx)) interface via JavaScript (NodeJS) with both simple requests and streaming requests. The extension uses the [inx.proto](https://github.com/iotaledger/inx/blob/develop/proto/inx.proto) file to generate the required gRPC client to connect to HORNET. [gRPC](https://grpc.io/) is a modern open source high performance Remote Procedure Call (RPC) framework that can run in any environment.
```

"interface" is not part of the name and should not be capitalized. "JavaScript" is a name and should be capitalized by its creator's spelling.

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +Run the Node.js initializer to configure the project.
```suggestion
Run the Node.js initializer to configure the project:

```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +Overwrite the `package.json` file with the following content.
```suggestion
Overwrite the `package.json` file with the following content:

```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +Create a new folder for the tutorial in a location of your choice and navigate to it.
```suggestion
Create a new folder for the tutorial in a location of your choice and navigate to it:
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +Install new dependencies.
```suggestion
Install new dependencies:

```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +Create new file `config.js` and add the following code.
```suggestion
#### Prepare configuration file

Create new file `config.js` and add the following code:

```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +
```suggestion
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +
```suggestion
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +```javascript
```suggestion
### Prepare and run files for simple requests

#### Create new file `ReadBlock.js` and add the following code.

```javascript
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +```javascript
```suggestion
#### Create new file `ReadNodeConfiguration.js` and add the following code.

```javascript

```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +```sh
```suggestion
#### Run `ListenToBlocks.js`

```sh
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +```javascript
```suggestion
#### Create new file `ListenToLatestMilestones.js` and add the following code.

```javascript
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +```sh
```suggestion
#### Run `ListenToLatestMilestones.js`

```sh
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +```javascript
```suggestion
#### Create new file `ReadUnspentOutputs.js` and add the following code.

```javascript
```

2022-08-08 09:32 UTC, aleksei-korolev commented on content/tutorials/single-page-tutorials/hornet-inx-interaction.md
> +```sh
```suggestion
#### Run `ReadUnspentOutputs.js`

```sh
```

2022-08-15 07:17 UTC, aleksei-korolev approved these changes
i apruv

2022-08-15 11:43 UTC, merged