Update value-transfer.md
iota-community/iota-wiki pull request #89
Opened 2021-07-27 06:51 UTC by Phyloiota

starting content

# Description of change

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix
- Documentation Enhancment

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the wiki locally and tested that all external links work

2021-08-03 23:22 UTC, Phyloiota commented
also here, can be published and extended, improved

2021-08-09 19:59 UTC, Dr-Electron requested changes

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +To transfer 10 i to Bob, Charlie must attach a value message to the Tangle. To do so, he needs between 1 and 8 tip messages that he can attach his own message.
```suggestion
To transfer 10 i to Bob, Charlie must attach a value message to the Tangle. For that, he needs between 1 and 8 tip messages that he can attach to his own message.
```

To, To, To :trollface:

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +* The ledger state is a record of all the value message that have transferred IOTA tokens in the Tangle, including the state of all balances on addresses. This state must always be balanced: The tota
```suggestion
* The ledger state is a record of all the value message that have transferred IOTA tokens in the Tangle, including the state of all balances on addresses. This state must always be balanced: The total number of IOTA tokens must always add up to the total supply.
```

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +Messages in the Tangle are confirmed by special messages called milestones. Those milestones are issued by a special node called Coordinator, that is operated by the IOTA Foundation and is therefore
```suggestion
Messages in the Tangle are confirmed by special messages called milestones. Those milestones are issued by a special node called Coordinator, that is operated by the IOTA Foundation and is therefore still a centralized part of the Consensus.
```

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +Lets go a bit more into details and observe the single stepd taken by the participants:
```suggestion
Let's go a bit more into details and observe the single steps taken by the participants:
```

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +But also simple command-line tools for professional users like the
```suggestion
But also simple command-line tools for professional users, like the 
```

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +Machines, sensors, and devices, etc will use the code of the IOTA Wallet Libraries to create and execute the transactions autonomously.
```suggestion
Machines, sensors, and devices, etc. will use the code of the IOTA Wallet Libraries to create and execute the transactions autonomously.
```

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +This signed transaction payload must contain a digital signature that guarantees that the sender of the transaction is the owner of the address where those funds are stored at the moment. This is gua
```suggestion
This signed transaction payload must contain a digital signature that guarantees that the sender of the transaction is the owner of the address where those funds are stored at the moment. This is guaranteed through signing the transaction with the private key of that address. A public key, that is also part of this message, will be used to validate the ownership over those funds. Read more about how private and public keys work together to establish this here:
```

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +The next step will be that the client connects to a node in the IOTA network and asks this node for valid tips to include into the message. After the tips (1 - 8 previous already confirmed messages o
```suggestion
The next step will be that the client connects to a node in the IOTA network and asks this node for valid tips to include into the message. After the tips (1 - 8 previous already confirmed messages of the tangle) are known to the client, they can be included into the message and therefore create a reference path for this message in the Tangle. Finally, the client now submits this message (that includes the transaction payload) for validation and processing to the node.
```

2021-08-09 19:59 UTC, Dr-Electron commented on docs/learn/about-iota/value-transfer.md
> +If all bits of the message are readable for the node and the node detects the signed transaction payload included in the message a validation process starts.
```suggestion
If all bits of the message are readable for the node and the node detects the signed transaction payload included in the message, a validation process starts.
```

2021-08-10 19:47 UTC, Dr-Electron approved these changes

2021-08-10 19:47 UTC, merged