Update an-introduction-to-iota.md
iota-community/iota-wiki pull request #90
Opened 2021-08-01 02:48 UTC by Phyloiota

created draft content

# Description of change

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix
- Documentation Enhancment

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the wiki locally and tested that all external links work

2021-08-03 23:20 UTC, Phyloiota commented
as a starting point okay, can be extended from here on

2021-08-09 19:44 UTC, Dr-Electron requested changes

2021-08-09 19:44 UTC, Dr-Electron commented on docs/learn/about-iota/an-introduction-to-iota.md
> +**This topic describes some of the main differences between the Tangle and a blockchain.**
```suggestion
**This topic describes some main differences between the Tangle and a blockchain.**
```
Sound nicer to me :)

2021-08-09 19:44 UTC, Dr-Electron commented on docs/learn/about-iota/an-introduction-to-iota.md
> +As a result, requiring PoW secures blockchain networks by making it difficult to attack, change, or stop. The more miners that mine, the more the secure the network.
```suggestion
As a result, requiring PoW secures blockchain networks by making it difficult to attack, change, or stop. The more miners participate, the more secure the network is.
```

Sounded a little weird to me. Not sure if m suggestion is better 😅

2021-08-09 19:44 UTC, Dr-Electron commented on docs/learn/about-iota/an-introduction-to-iota.md
> +Currently messages will only considered valid if they have a refference to a milestone. These milestones are issued by a special network node - the Coordinator.
```suggestion
Currently messages will only be considered valid if they have a reference to a milestone. These milestones are issued by a special network node - the Coordinator.
```

2021-08-09 19:44 UTC, Dr-Electron commented on docs/learn/about-iota/an-introduction-to-iota.md
> + - The Coordinator is temporary. We will transition into removing the Coordinator:Coordicide in the upcomming IOTA 2.0 Metwork. Below is how the Coordinator is currently employed within IOTA.
```suggestion
 - The Coordinator is temporary. We will transition into removing the Coordinator: Coordicide in the upcoming IOTA 2.0 network. Below is how the Coordinator is currently employed within IOTA.
```

2021-08-09 19:44 UTC, Dr-Electron commented on docs/learn/about-iota/an-introduction-to-iota.md
> +To make sure that new messages always have a chance of being confirmed, the Coordinator sends indexed milestones at regular intervals. This way, nodes can compare the indexes of their milestones to c
```suggestion
To make sure that new messages always have a chance of being confirmed, the Coordinator sends indexed milestones at regular intervals. This way, nodes can compare the indexes of their milestones to check whether they are synchronized with the rest of the network.
```

2021-08-10 19:48 UTC, Dr-Electron approved these changes

2021-08-10 19:49 UTC, merged