Create node-software.md
iota-community/iota-wiki pull request #94
Opened 2021-08-01 13:13 UTC by Phyloiota

created content

# Description of change

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation Fix
- Documentation Enhancment

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have tested the wiki locally and tested that all external links work

2021-08-03 20:44 UTC, Dr-Electron requested changes

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +description: IOTA networks consist of interconnected nodes that run the same node software. We introduce the different available Types and provide guides that will help in setting those nodes up.
```suggestion
description: IOTA networks consist of interconnected nodes that run the same node software. We introduce the different available types and provide guides that will help in setting those nodes up.
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- [Hornet documentation - setup a node](https://hornet.docs.iota.org/getting_started/installation_steps.html/)
```suggestion
- [Hornet documentation - set up a node](https://hornet.docs.iota.org/getting_started/installation_steps.html/)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +* Step by Step guide for Windows users by Phylo:
```suggestion
* Step-by-Step guide for Windows users by Phylo: 
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- [Bee Github](https://github.com/iotaledger/bee)
```suggestion
- [Bee GitHub](https://github.com/iotaledger/bee)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +### BEE Instalation guides
```suggestion
### BEE Installation guides
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- [Setup a BEE Node](https://bee.docs.iota.org/setup_a_node)
```suggestion
- [Set up a BEE Node](https://bee.docs.iota.org/setup_a_node)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +## Goshimmer
```suggestion
## GoShimmer
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +The software is written in Go and is currently the software used in the IOTA 2.0 DevNet where the upcoming IOTA 2.0 version without a coordinator node is tested and optimized in collaboration with a
```suggestion
The software is written in Go and is currently the software used in the IOTA 2.0 DevNet where the upcoming IOTA 2.0 version without a coordinator node is tested and optimized in collaboration with a huge amount of community contributors. GoShimmer allows testing and analyzing all upcoming features of IOTA and is therefore an essential part of the ongoing IOTA Research.
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +Goshimmer will not be developed as an upcoming Mainnet node Software.
```suggestion
GoShimmer will not be developed as an upcoming Mainnet node Software.
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +The full documentation for Goshimmer can be found here:
```suggestion
The full documentation for GoShimmer can be found here:
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- [Goshimmer Documentation](https://goshimmer.docs.iota.org/)
```suggestion
- [GoShimmer Documentation](https://goshimmer.docs.iota.org/)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- [Goshimmer GitHub](https://github.com/iotaledger/Goshimmer)
```suggestion
- [GoShimmer GitHub](https://github.com/iotaledger/goshimmer)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +### Goshimmer Installation guides
```suggestion
### GoShimmer Installation guides
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- [Goshimmer Node Setup](https://goshimmer.docs.iota.org/docs/tutorials/setup)
```suggestion
- [GoShimmer Node Setup](https://goshimmer.docs.iota.org/docs/tutorials/setup)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +### Goshimmer community tutorials:
```suggestion
### GoShimmer community tutorials:
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- Nuriels Goshimmer Playbook: [Nuriel77 Goshimmer](https://github.com/nuriel77/goshimmer-playbook)
```suggestion
- Nuriels GoShimmer Playbook: [Nuriel77 GoShimmer](https://github.com/nuriel77/goshimmer-playbook)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +- DeMichelle Shell Script: [Demichelle Goshimmer](https://github.com/demichele/install-goshimmer)
```suggestion
- DeMichelle Shell Script: [DeMichelle GoShimmer](https://github.com/demichele/install-goshimmer)
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +## WASP Smartcontract Node
```suggestion
## WASP Smart Contract Node
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +Wasp is still a work in progress and is purely for development and testing purposes. It runs in combination with Goshimmer Nodes on the IOTA 2.0 Devnet.
```suggestion
Wasp is still a work in progress and is purely for development and testing purposes. It runs in combination with GoShimmer Nodes on the IOTA 2.0 DevNet.
```

2021-08-03 20:44 UTC, Dr-Electron commented on docs/participate/support-the-network/node-software.md
> +The full documentation for WASP Smartcontract Nodes can be found here:
```suggestion
The full documentation for WASP Smart Contract Nodes can be found here:
```

2021-08-03 23:11 UTC, Phyloiota commented
Lol, you really got me on this one @Dr-Electron    :)

2021-08-04 11:36 UTC, Dr-Electron approved these changes

2021-08-04 11:36 UTC, merged